### ISSUE TITLE
Override the APP_DOMAIN value when deploying the docker container

### ISSUE THREAD

**Issue by nothingmn** [supermasita/geoip-flask#5]
Hello,

Are we able to override the APP_DOMAIN value when deploying the docker container?

Thank you.

**Comment by supermasita** [comment]
Hi! That was not possible, but I've just merged a change that should allow it. When you pull the updated Docker image is updated in Docker Hub (unless you are building your own), you will need to do something like: 
```
docker run -e GEOIP_APP_DOMAIN=example.com ...
```
Let me know if it works as expected. 

Thanks!

**Comment by supermasita** [comment]
Please note that `GEOIP_APP_DOMAIN` has been renamed to `GEOIP_APP_ENDPOINT` and now it expects to also include the scheme (example: `http://example.com`)
